# Generated by Django 2.0.13 on 2019-06-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('correo', models.CharField(blank=True, max_length=2550)),
                ('direccion', models.CharField(blank=True, max_length=2550)),
                ('num_tarj', models.CharField(blank=True, max_length=2550)),
                ('banco', models.CharField(blank=True, max_length=2550)),
                ('patente', models.CharField(blank=True, max_length=2550)),
                ('marca', models.CharField(blank=True, max_length=2550)),
                ('modelo', models.CharField(blank=True, max_length=2550)),
                ('año', models.CharField(blank=True, max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('rut', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=400)),
                ('telefono', models.CharField(max_length=9)),
                ('correo', models.CharField(blank=True, max_length=2550)),
                ('direccion', models.CharField(blank=True, max_length=2550)),
                ('num_cuenta', models.CharField(blank=True, max_length=2550)),
                ('esta_detall', models.CharField(blank=True, max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, max_length=2550)),
                ('descripcion', models.CharField(blank=True, max_length=2550)),
                ('latitud', models.FloatField(null=True)),
                ('longitud', models.FloatField(null=True)),
                ('Dueño', models.ManyToManyField(to='app.Dueño')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
