# Generated by Django 2.0.13 on 2019-06-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190628_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamiento',
            name='Dueño',
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='dueño',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Dueño'),
        ),
    ]
