# Generated by Django 2.0.13 on 2019-06-28 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190628_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='dueño',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Dueño',
        ),
    ]
