# Generated by Django 2.0.13 on 2019-06-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190628_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='direccion',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
    ]
