# Generated by Django 2.0.13 on 2019-06-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190628_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('Arrendatario', 'Arrendatario'), ('Cliente', 'Cliente')], default='Cliente', max_length=30, null=True),
        ),
    ]
